### ISSUE TITLE
[BUG] Unable to validate Radiant Silvergun BUP file

### ISSUE THREAD

**Issue by privateye** [slinga-homebrew/Save-Game-BUP-Scripts#1]
`bup_parse.py` is unable to validate `RADIANT_S_G.BUP` which also means that the raw save file cannot be extracted from it. Running the command `bup_parse.py --input_bup RADIANT_S_G.BUP --extract_raw_save` gives the following error:

![1](https://user-images.githubusercontent.com/69020283/115926424-b97eea80-a47a-11eb-8be9-61e5153894ec.png)

`RADIANT_S_G.BUP` was obtained by dumping my Radiant Silvergun save file to the [Saturn Gamer's Cartridge](https://ppcenter.webou.net/satcart/#gamers). Out of my personal collection of 50+ BUP files, this is the only one that produces this error. A copy of `RADIANT_S_G.BUP` can be found below:

[RADIANT_S_G.zip](https://github.com/slinga-homebrew/Save-Game-BUP-Scripts/files/6367972/RADIANT_S_G.zip)

**Comment by slinga-homebrew** [comment]
Changing offset 0x25 from 0xFF to 0x00 in the RADIANT_S_G.BUP file seems to fix this issue. 

The question is what is correct behavior. Should I just parse until I find the first NULL byte in the comment? From my understanding the comment string should be valid SJIS. Cafe-Alpha mentioned that there are games that put data there as well. I think I will reach out to him for advice.
